import type { Metadata } from "next";
import "../app/globals.css";
import { MinimizedCallBar } from "@/components/MinimizedCallBar";

// You can define metadata for your application here
export const metadata: Metadata = {
  title: "Echo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // The <html> tag is required here
    <html lang="en">
      {/* The <body> tag is also required */}
      <body>
        {/* 'children' will be replaced by your page content */}
        {children}
        {/* Minimized call bar - shows when user navigates away from active call */}
        <MinimizedCallBar />
      </body>
    </html>
  );
}